generator:
  name: biggan
  nlabels: 200
discriminator:
  name: biggan
biggan:
  dataset: 'C100'
  augment: False
  num_workers: 8
  pin_memory: True
  shuffle: True
  load_in_mem: False
  use_multiepoch_sampler: False
  loss_type: 'xx'
  AC: False
  AC_weight: 1.0
  Pac: False
  G_param: 'SN'
  D_param: 'SN'
  G_ch: 64
  D_ch: 64
  G_depth: 1
  D_depth: 1
  D_wide: True
  G_shared: False
  shared_dim: 0
  dim_z: 128
  z_var: 1.0
  hier: False
  mybn: False
  G_nl: 'relu'
  D_nl: 'relu'
  G_attn: '0'
  D_attn: '0'
  norm_style: 'bn'
  seed: 2019
  G_init: 'N02'
  D_init: 'N02'
  skip_init: False
  G_lr: 0.0002
  D_lr: 0.0002
  G_B1: 0.0
  D_B1: 0.0
  G_B2: 0.999
  D_B2: 0.999
  batch_size: 100
  G_batch_size: 0
  num_G_steps: 1
  num_G_accumulations: 1
  num_D_steps: 2
  num_D_accumulations: 1
  split_D: False
  num_epochs: 500
  parallel: True
  accumulate_stats: False
  num_standing_accumulations: 16
  G_eval_mode: False
  save_every: 2
  num_save_copies: 2
  num_best_copies: 5
  which_best: 'IS'
  no_fid: False
  test_every: 2
  num_inception_images: 50000
  base_root: '../Biggan_result'
  data_root: '../Biggan_result/data'
  weights_root: '../Biggan_result/weights'
  logs_root: '../Biggan_result/logs'
  samples_root: '../Biggan_result/samples'
  name_suffix: ''
  experiment_name: ''
  config_from_name: False
  ema: True
  ema_decay: 0.9999
  use_ema: True
  ema_start: 10000
  toggle_grads: True
  load_weights: ''
  resume: False
  # logstyle: %3.3e
  resolution: 32
  n_classes: 200
z_dist:
  type: gauss
  dim: 128 # it should be equal to biggans
clusterer:
  name: scan_guide
  nimgs: 50000
  kwargs:
    k_value: 200
    model_path:  ./clusterers/pretrained/partitioner_iresnet_k200/cifar-10/scan/model.pth.tar
    setup: scan
    num_heads: 1
    backbone_name: iresnet
inherit_from: configs/cifar/default.yaml
training:
  out_dir: output/cifar/scan_guide_biggan
  gan_type: hinge
  optimizer: adam
  lr_g: 0.0002
  lr_d: 0.0002
  beta1: 0.0
  beta2: 0.999
  batch_size: 100
  backup_every: 5000
  log_every: 1000
resnet:
  weight_guide: 6.0
  annealing: -0.00012
  min_weight_guide: 0.0